### ISSUE TITLE
<% htmlWebpackPlugin.files.js.forEach(function (src) { %> <% }) %> on http://localhost:8080/demo/

### ISSUE THREAD

**Issue by irfanshehzadsandhu** [ringcentral/ringcentral-web-phone#322]

**Comment by vyshakhbabji** [comment]
Can you explain what the issue is ?

**Comment by irfanshehzadsandhu** [comment]
I did the following steps 
1 - Cloned the repository
2 - npm install
3 - npm start
After these steps when I opened the http://localhost:8080/demo/ in a browser Its showing me this error <% htmlWebpackPlugin.files.js.forEach(function (src) { %> <% }) %> on http://localhost:8080/demo/ on a page
.Am I missing something? Any setting of environment variables ?

**Comment by z0lo13** [comment]
@irfanshehzadsandhu have you find the solution?

**Comment by tylerlong** [comment]
Try the latest version. 

```
yarn start 
```

And visit http://localhost:8080



I believe the root cause of the issue is: instead of "npm start", you may run "npm server" by mistake. And that command simply start a http server and listen to http://localhost:8080, and since it is just a http server, not a webpack dev server, it won't work.   And also because of that, the 8080 port is taken. And "npm start" will take 8081 instead.   However, you kept testing 8080 which won't never work.

Above is just my assumption, I believe we don't have such an issue any more.  And we also switched from npm to yarn.
