### ISSUE TITLE
Incoming works, outgoing does not

### ISSUE THREAD

**Issue by FlandersBurger** [ringcentral/ringcentral-web-phone#371]
I'm having trouble establishing an outgoing call (note I'm using sandbox within RingCentral).
The session looks to be created correctly but none of the functions work attached to it.
The phone I'm testing with does not ring.
When I try sessions.accept(), it tells me that accept is not a function, when it clearly is a function judging by the console output.
It almost looks like the call is immediately terminated as when I call bye on the session, it says it's already terminated.

What is supposed to happen after invite() ? Does the session need to be accepted? 

<img width="559" alt="image" src="https://user-images.githubusercontent.com/8195826/216712268-0a3b5663-3e80-4fd1-b96f-23c711dbdc04.png">

<img width="558" alt="image" src="https://user-images.githubusercontent.com/8195826/216712688-6c73b996-dca3-422b-82be-3e5d64e57928.png">

**Comment by tylerlong** [comment]
For **outbound** call you don't need to **accept**. If you have a production account, please try to reproduce the issue in production environment and post updates here. Thanks.

**Comment by tylerlong** [comment]
It sounds more like an account issue or coding issue instead of SDK issue.
Please try to reproduce the issue here https://ringcentral.github.io/ringcentral-web-phone
And refer to the code here: https://github.com/ringcentral/ringcentral-web-phone/tree/master/demo

If you still cannot make it work, please create a ticket here: https://developers.ringcentral.com/support/create-case

Feel free to open a new GitHub issue if you believe something is wrong with the SDK.
